//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertIdentity) DeepCopyInto(out *CertIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertIdentity.
func (in *CertIdentity) DeepCopy() *CertIdentity {
	if in == nil {
		return nil
	}
	out := new(CertIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertIdentityList) DeepCopyInto(out *CertIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CertIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertIdentityList.
func (in *CertIdentityList) DeepCopy() *CertIdentityList {
	if in == nil {
		return nil
	}
	out := new(CertIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CertIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertIdentitySpec) DeepCopyInto(out *CertIdentitySpec) {
	*out = *in
	in.CertIdentitySpecBase.DeepCopyInto(&out.CertIdentitySpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertIdentitySpec.
func (in *CertIdentitySpec) DeepCopy() *CertIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(CertIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertIdentitySpecBase) DeepCopyInto(out *CertIdentitySpecBase) {
	*out = *in
	if in.EZCAURL != nil {
		in, out := &in.EZCAURL, &out.EZCAURL
		*out = new(string)
		**out = **in
	}
	if in.TenantID != nil {
		in, out := &in.TenantID, &out.TenantID
		*out = new(string)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(string)
		**out = **in
	}
	if in.AppObjectID != nil {
		in, out := &in.AppObjectID, &out.AppObjectID
		*out = new(string)
		**out = **in
	}
	if in.AppInsightsConnString != nil {
		in, out := &in.AppInsightsConnString, &out.AppInsightsConnString
		*out = new(string)
		**out = **in
	}
	if in.KeyVault != nil {
		in, out := &in.KeyVault, &out.KeyVault
		*out = new(KeyVaultSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertIdentitySpecBase.
func (in *CertIdentitySpecBase) DeepCopy() *CertIdentitySpecBase {
	if in == nil {
		return nil
	}
	out := new(CertIdentitySpecBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertIdentityStatus) DeepCopyInto(out *CertIdentityStatus) {
	*out = *in
	in.CertIdentityStatusBase.DeepCopyInto(&out.CertIdentityStatusBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertIdentityStatus.
func (in *CertIdentityStatus) DeepCopy() *CertIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(CertIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertIdentityStatusBase) DeepCopyInto(out *CertIdentityStatusBase) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NotBefore != nil {
		in, out := &in.NotBefore, &out.NotBefore
		*out = (*in).DeepCopy()
	}
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
	if in.LastRenewalTime != nil {
		in, out := &in.LastRenewalTime, &out.LastRenewalTime
		*out = (*in).DeepCopy()
	}
	if in.PendingSince != nil {
		in, out := &in.PendingSince, &out.PendingSince
		*out = (*in).DeepCopy()
	}
	if in.ManagedKeyCredentials != nil {
		in, out := &in.ManagedKeyCredentials, &out.ManagedKeyCredentials
		*out = make([]ManagedKeyCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertIdentityStatusBase.
func (in *CertIdentityStatusBase) DeepCopy() *CertIdentityStatusBase {
	if in == nil {
		return nil
	}
	out := new(CertIdentityStatusBase)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCertIdentity) DeepCopyInto(out *ClusterCertIdentity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCertIdentity.
func (in *ClusterCertIdentity) DeepCopy() *ClusterCertIdentity {
	if in == nil {
		return nil
	}
	out := new(ClusterCertIdentity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCertIdentity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCertIdentityList) DeepCopyInto(out *ClusterCertIdentityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ClusterCertIdentity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCertIdentityList.
func (in *ClusterCertIdentityList) DeepCopy() *ClusterCertIdentityList {
	if in == nil {
		return nil
	}
	out := new(ClusterCertIdentityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClusterCertIdentityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCertIdentitySpec) DeepCopyInto(out *ClusterCertIdentitySpec) {
	*out = *in
	in.CertIdentitySpecBase.DeepCopyInto(&out.CertIdentitySpecBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCertIdentitySpec.
func (in *ClusterCertIdentitySpec) DeepCopy() *ClusterCertIdentitySpec {
	if in == nil {
		return nil
	}
	out := new(ClusterCertIdentitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterCertIdentityStatus) DeepCopyInto(out *ClusterCertIdentityStatus) {
	*out = *in
	in.CertIdentityStatusBase.DeepCopyInto(&out.CertIdentityStatusBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterCertIdentityStatus.
func (in *ClusterCertIdentityStatus) DeepCopy() *ClusterCertIdentityStatus {
	if in == nil {
		return nil
	}
	out := new(ClusterCertIdentityStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IdentityRefSpec) DeepCopyInto(out *IdentityRefSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IdentityRefSpec.
func (in *IdentityRefSpec) DeepCopy() *IdentityRefSpec {
	if in == nil {
		return nil
	}
	out := new(IdentityRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeyVaultSpec) DeepCopyInto(out *KeyVaultSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeyVaultSpec.
func (in *KeyVaultSpec) DeepCopy() *KeyVaultSpec {
	if in == nil {
		return nil
	}
	out := new(KeyVaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCredential) DeepCopyInto(out *ManagedCredential) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCredential.
func (in *ManagedCredential) DeepCopy() *ManagedCredential {
	if in == nil {
		return nil
	}
	out := new(ManagedCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedCredential) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCredentialList) DeepCopyInto(out *ManagedCredentialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ManagedCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCredentialList.
func (in *ManagedCredentialList) DeepCopy() *ManagedCredentialList {
	if in == nil {
		return nil
	}
	out := new(ManagedCredentialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ManagedCredentialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCredentialSpec) DeepCopyInto(out *ManagedCredentialSpec) {
	*out = *in
	in.CertIdentitySpecBase.DeepCopyInto(&out.CertIdentitySpecBase)
	if in.DNSNames != nil {
		in, out := &in.DNSNames, &out.DNSNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.IPAddresses != nil {
		in, out := &in.IPAddresses, &out.IPAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.URIs != nil {
		in, out := &in.URIs, &out.URIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.EmailAddresses != nil {
		in, out := &in.EmailAddresses, &out.EmailAddresses
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.KeyUsages != nil {
		in, out := &in.KeyUsages, &out.KeyUsages
		*out = make([]KeyUsage, len(*in))
		copy(*out, *in)
	}
	if in.ExtendedKeyUsages != nil {
		in, out := &in.ExtendedKeyUsages, &out.ExtendedKeyUsages
		*out = make([]ExtKeyUsage, len(*in))
		copy(*out, *in)
	}
	out.IdentityRef = in.IdentityRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCredentialSpec.
func (in *ManagedCredentialSpec) DeepCopy() *ManagedCredentialSpec {
	if in == nil {
		return nil
	}
	out := new(ManagedCredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedCredentialStatus) DeepCopyInto(out *ManagedCredentialStatus) {
	*out = *in
	in.CertIdentityStatusBase.DeepCopyInto(&out.CertIdentityStatusBase)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedCredentialStatus.
func (in *ManagedCredentialStatus) DeepCopy() *ManagedCredentialStatus {
	if in == nil {
		return nil
	}
	out := new(ManagedCredentialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagedKeyCredential) DeepCopyInto(out *ManagedKeyCredential) {
	*out = *in
	in.NotAfter.DeepCopyInto(&out.NotAfter)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagedKeyCredential.
func (in *ManagedKeyCredential) DeepCopy() *ManagedKeyCredential {
	if in == nil {
		return nil
	}
	out := new(ManagedKeyCredential)
	in.DeepCopyInto(out)
	return out
}
